---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-app
      version: blue
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: my-nginx-app
        version: blue
    spec:
      containers:
      - name:my-nginx-container
        image: poojakk123/hellowhale
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: my-nginx-svc
  labels:
    app: my-nginx-app
spec:
  selector:
    app: my-nginx-app
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
---
